-- First, remove the table if it exists
drop table if exists bookmarks;

-- Create the table anew
create table bookmarks (
  id INTEGER primary key generated by default as identity,
  customer_name text,
  phone VARCHAR(30)
);

-- insert some test data
-- Using a multi-row insert statement here
insert into bookmarks (title, url)
values
  ('Sam', '555-1234'),
  ('Ham', '555-4321'),
  ('Ram', '555-5678');

